### PR TITLE
Fix build issues with vs2019

### LINKED ISSUE #35: Ball examples fails to link on Windows 10 MSVC
**Describe the bug**

The ball example fails to link on Windows 10 MSVC.

**To Reproduce**

```
$ git clone https://github.com/EmbarkStudios/physx-rs.git --depth 1 --recursive
$ cd physx-rs
$ cargo run --example ball
    Updating crates.io index
   Compiling cc v1.0.47
   Compiling cmake v0.1.42
   Compiling physx-sys v0.2.1+4.1.1 (D:\projects\physx-rs\physx-sys)
error: could not find native static library `PhysXVehicle_static_64`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `physx-sys`.
```

Running `cargo test` also produces a link error:

```
LINK : fatal error LNK1181: cannot open input file 'PhysXVehicle_static_64.lib'
```

**Device:**
```
$ rustc --version --verbose
rustc 1.39.0 (4560ea788 2019-11-04)
binary: rustc
commit-hash: 4560ea788cb760f0a34127156c78e2552949f734
commit-date: 2019-11-04
host: x86_64-pc-windows-msvc
release: 1.39.0
LLVM version: 9.0
```

**Additional context**
I generally use a Cygwin/Git-bash shell on windows, but I also tested with a `cmd` prompt to rule out any shell/path related issues. The results were the same.

### PR DESCRIPTION
**Pull request by h3r2tic**
Fixes #35 and missing typeinfo.h issues with Visual Studio 2019.

The linker error was caused by the wrong directory being used for build static libs. It is now discovered automatically by the `build.rs` script.

The PhysX submodule is updated to point to our fork which now includes a workaround for the missing include file.

Includes Visual Studio 2019 CI build config from #36.

### CODE REVIEW

File: physx-sys/build.rs [hunk 1]
```diff
@@ -3,23 +3,72 @@ use std::env;
...
+// "bin/mac.x86_64/debug"
+//
+// In order not to have to replicate the CMAKE logic, we will inspect all paths with the structure
+// "bin/*/debug" or "bin/*/profile", depending on the build profile passed to CMAKE.
+// Among those directories, we choose the one containing the most recently modified files.
+// This is to ensure that we find the correct folder even if it contains stale results from different compilers.
+fn locate_output_lib_dir(mut cmake_build_out: PathBuf, build_profile: &str) -> String {
+    use std::fs;
+
+    // Always witin the "bin" folder of the CMAKE output
```
Comment (Jake-Shadle) [inline physx-sys/build.rs]:
```suggestion
    // Always within the "bin" folder of the CMAKE output
```

Comment (h3r2tic) [reply physx-sys/build.rs]: Thanks!
